# This Dockerfile describes how to create the Drupal 6 container to
# serve legacy Drupal 6 sites.
# This will automatically be spun up from the ./scripts/run.sh script.
FROM dcycle/drupal:6

RUN drush dl \
	features-6.x-1.x-dev \
	cck-6.x-2.10 \
	admin_menu-6.x-3.x-dev \
	devel-6.x-1.25 \
	filefield-6.x-3.14 \
	imagefield-6.x-3.3 \
	-y

ADD docker-resources/drupal6/run.sh /run.sh
ADD docker-resources/drupal6/run-import.sh /run-import.sh
ADD docker-resources/drupal6/run-post-install.sh /run-post-install.sh
ADD docker-resources/drupal6/drupal6structure /var/www/html/sites/all/modules/features/drupal6structure

RUN cp /var/www/html/sites/default/default.settings.php ./sites/default/settings.php
RUN echo '$db_url = "mysql://drupal:drupal@drupal6database/drupal";' >> \
  /var/www/html/sites/default/settings.php

EXPOSE 80
